### ISSUE TITLE
Quardrant numbers left showing after save

### ISSUE THREAD

**Issue by marcpawl** [leberechtreinhold/dba3_tts#12]
1.  Create, multi player, create server
2. Load DBA 3.0 (Scripted)
3. Spawn Table, tropical
4. Check "Do not show rulers" to show the rulers, and the quadrant numbers
5. Games, Save, "rulers_on"
6. Menu, Main Menu, yes to exit
7. Create, multi player, create server
8. Load "rulers_on", "Load"
Rulers and numbers remain showing.
BUG:  "Do not show rulers" is unselected, should be selected with text "Show deployment rulers"
9. Select Do not Show  rulers
Rulers and numbers remain showing.
10.  Unselect "Show deployment rulers"
Rulers are removed:
BUG:  Numbers remain visible

**Comment by marcpawl** [comment]
WAG g_current_numbers is not being loaded.  So nothing is being removed in remove_deployment_lines.

**Comment by leberechtreinhold** [comment]
No variable is actually saved - in TTS, only the state of the objects is shown. That's why the text objects are in but the checkbox isn't.

For the next patch I will make that the loading actually removes any number.
